// <auto-generated />
//using System;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
//using TrackIT.Data;

//namespace TrackIT.Data.Migrations
//{
//    [DbContext(typeof(ApplicationDbContext))]
//    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
//    {
//        protected override void BuildModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "3.0.0")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128)
//                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.DeviceFlowCodes", b =>
//                {
//                    b.Property<string>("UserCode")
//                        .HasColumnType("nvarchar(200)")
//                        .HasMaxLength(200);

//                    b.Property<string>("ClientId")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(200)")
//                        .HasMaxLength(200);

//                    b.Property<DateTime>("CreationTime")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("Data")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)")
//                        .HasMaxLength(50000);

//                    b.Property<string>("DeviceCode")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(200)")
//                        .HasMaxLength(200);

//                    b.Property<DateTime?>("Expiration")
//                        .IsRequired()
//                        .HasColumnType("datetime2");

//                    b.Property<string>("SubjectId")
//                        .HasColumnType("nvarchar(200)")
//                        .HasMaxLength(200);

//                    b.HasKey("UserCode");

//                    b.HasIndex("DeviceCode")
//                        .IsUnique();

//                    b.HasIndex("Expiration");

//                    b.ToTable("DeviceCodes");
//                });

//            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.PersistedGrant", b =>
//                {
//                    b.Property<string>("Key")
//                        .HasColumnType("nvarchar(200)")
//                        .HasMaxLength(200);

//                    b.Property<string>("ClientId")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(200)")
//                        .HasMaxLength(200);

//                    b.Property<DateTime>("CreationTime")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("Data")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)")
//                        .HasMaxLength(50000);

//                    b.Property<DateTime?>("Expiration")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("SubjectId")
//                        .HasColumnType("nvarchar(200)")
//                        .HasMaxLength(200);

//                    b.Property<string>("Type")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(50)")
//                        .HasMaxLength(50);

//                    b.HasKey("Key");

//                    b.HasIndex("Expiration");

//                    b.HasIndex("SubjectId", "ClientId", "Type");

//                    b.ToTable("PersistedGrants");
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
//                {
//                    b.Property<string>("Id")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("ConcurrencyStamp")
//                        .IsConcurrencyToken()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Name")
//                        .HasColumnType("nvarchar(256)")
//                        .HasMaxLength(256);

//                    b.Property<string>("NormalizedName")
//                        .HasColumnType("nvarchar(256)")
//                        .HasMaxLength(256);

//                    b.HasKey("Id");

//                    b.HasIndex("NormalizedName")
//                        .IsUnique()
//                        .HasName("RoleNameIndex")
//                        .HasFilter("[NormalizedName] IS NOT NULL");

//                    b.ToTable("AspNetRoles");
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<string>("ClaimType")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("ClaimValue")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("RoleId")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(450)");

//                    b.HasKey("Id");

//                    b.HasIndex("RoleId");

//                    b.ToTable("AspNetRoleClaims");
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<string>("ClaimType")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("ClaimValue")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("UserId")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(450)");

//                    b.HasKey("Id");

//                    b.HasIndex("UserId");

//                    b.ToTable("AspNetUserClaims");
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
//                {
//                    b.Property<string>("LoginProvider")
//                        .HasColumnType("nvarchar(128)")
//                        .HasMaxLength(128);

//                    b.Property<string>("ProviderKey")
//                        .HasColumnType("nvarchar(128)")
//                        .HasMaxLength(128);

//                    b.Property<string>("ProviderDisplayName")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("UserId")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(450)");

//                    b.HasKey("LoginProvider", "ProviderKey");

//                    b.HasIndex("UserId");

//                    b.ToTable("AspNetUserLogins");
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
//                {
//                    b.Property<string>("UserId")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("RoleId")
//                        .HasColumnType("nvarchar(450)");

//                    b.HasKey("UserId", "RoleId");

//                    b.HasIndex("RoleId");

//                    b.ToTable("AspNetUserRoles");
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
//                {
//                    b.Property<string>("UserId")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("LoginProvider")
//                        .HasColumnType("nvarchar(128)")
//                        .HasMaxLength(128);

//                    b.Property<string>("Name")
//                        .HasColumnType("nvarchar(128)")
//                        .HasMaxLength(128);

//                    b.Property<string>("Value")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("UserId", "LoginProvider", "Name");

//                    b.ToTable("AspNetUserTokens");
//                });

//            modelBuilder.Entity("TrackIT.Models.ApplicationUser", b =>
//                {
//                    b.Property<string>("Id")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<int>("AccessFailedCount")
//                        .HasColumnType("int");

//                    b.Property<string>("ConcurrencyStamp")
//                        .IsConcurrencyToken()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int?>("CustomerId")
//                        .HasColumnType("int");

//                    b.Property<string>("Email")
//                        .HasColumnType("nvarchar(256)")
//                        .HasMaxLength(256);

//                    b.Property<bool>("EmailConfirmed")
//                        .HasColumnType("bit");

//                    b.Property<string>("FirstName")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("LastName")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("LockoutEnabled")
//                        .HasColumnType("bit");

//                    b.Property<DateTimeOffset?>("LockoutEnd")
//                        .HasColumnType("datetimeoffset");

//                    b.Property<string>("NormalizedEmail")
//                        .HasColumnType("nvarchar(256)")
//                        .HasMaxLength(256);

//                    b.Property<string>("NormalizedUserName")
//                        .HasColumnType("nvarchar(256)")
//                        .HasMaxLength(256);

//                    b.Property<string>("PasswordHash")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("PhoneNumber")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("PhoneNumberConfirmed")
//                        .HasColumnType("bit");

//                    b.Property<string>("SecurityStamp")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("TwoFactorEnabled")
//                        .HasColumnType("bit");

//                    b.Property<string>("UserName")
//                        .HasColumnType("nvarchar(256)")
//                        .HasMaxLength(256);

//                    b.HasKey("Id");

//                    b.HasIndex("CustomerId");

//                    b.HasIndex("NormalizedEmail")
//                        .HasName("EmailIndex");

//                    b.HasIndex("NormalizedUserName")
//                        .IsUnique()
//                        .HasName("UserNameIndex")
//                        .HasFilter("[NormalizedUserName] IS NOT NULL");

//                    b.ToTable("AspNetUsers");
//                });

//            modelBuilder.Entity("TrackIT.Models.Cases", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<DateTime?>("DateApplied")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime?>("DateApproved")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime?>("DateAssigned")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime?>("DateAwaitApproval")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime?>("DateCompleted")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime?>("DateOpened")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime?>("Deadline")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("Description")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<float?>("EstimatedTimeHours")
//                        .HasColumnType("real");

//                    b.Property<string>("FilesUploaded")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int?>("SoftwareId")
//                        .HasColumnType("int");

//                    b.Property<string>("StaffAssigned")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("Status")
//                        .HasColumnType("int");

//                    b.Property<float?>("TimeSpentHours")
//                        .HasColumnType("real");

//                    b.Property<string>("Title")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("Type")
//                        .HasColumnType("int");

//                    b.Property<int>("UrgencyLevel")
//                        .HasColumnType("int");

//                    b.Property<string>("UserId")
//                        .HasColumnType("nvarchar(450)");

//                    b.HasKey("Id");

//                    b.HasIndex("SoftwareId");

//                    b.HasIndex("UserId");

//                    b.ToTable("Cases");
//                });

//            modelBuilder.Entity("TrackIT.Models.Customers", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<string>("Address1")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Address2")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Address3")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Address4")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Email")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Name")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("PhoneNumber")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("Customers");
//                });

//            modelBuilder.Entity("TrackIT.Models.Messages", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<int?>("CaseId")
//                        .HasColumnType("int");

//                    b.Property<bool>("IsEmployee")
//                        .HasColumnType("bit");

//                    b.Property<string>("Message")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("TimeStamp")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("UserId")
//                        .HasColumnType("nvarchar(450)");

//                    b.HasKey("Id");

//                    b.HasIndex("CaseId");

//                    b.HasIndex("UserId");

//                    b.ToTable("Messages");
//                });

//            modelBuilder.Entity("TrackIT.Models.Software", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<string>("Name")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("Software");
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
//                {
//                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
//                        .WithMany()
//                        .HasForeignKey("RoleId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
//                {
//                    b.HasOne("TrackIT.Models.ApplicationUser", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
//                {
//                    b.HasOne("TrackIT.Models.ApplicationUser", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
//                {
//                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
//                        .WithMany()
//                        .HasForeignKey("RoleId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("TrackIT.Models.ApplicationUser", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
//                {
//                    b.HasOne("TrackIT.Models.ApplicationUser", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("TrackIT.Models.ApplicationUser", b =>
//                {
//                    b.HasOne("TrackIT.Models.Customers", "Customer")
//                        .WithMany()
//                        .HasForeignKey("CustomerId");
//                });

//            modelBuilder.Entity("TrackIT.Models.Cases", b =>
//                {
//                    b.HasOne("TrackIT.Models.Software", "Software")
//                        .WithMany()
//                        .HasForeignKey("SoftwareId");

//                    b.HasOne("TrackIT.Models.ApplicationUser", "User")
//                        .WithMany()
//                        .HasForeignKey("UserId");
//                });

//            modelBuilder.Entity("TrackIT.Models.Messages", b =>
//                {
//                    b.HasOne("TrackIT.Models.Cases", "Case")
//                        .WithMany()
//                        .HasForeignKey("CaseId");

//                    b.HasOne("TrackIT.Models.ApplicationUser", "User")
//                        .WithMany()
//                        .HasForeignKey("UserId");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
